apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: projet-indiv
spec:
  replicas: 1
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: frontend
          image: projet-indiv-frontend:0.0.1
          env:
            - name: BACKEND_HOST
              value: backend-svc
            - name: BACKEND_PORT
              value: "80"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: projet-indiv
spec:
  type: NodePort
  selector: { app: frontend }
  ports:
    - port: 80
      targetPort: 80
